
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Point;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Juan José JV
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        setLocationRelativeTo(null);//Centrar la ventana
        setResizable(false);//Bloquear maximizar ventana
        setTitle("Ajedrez Demo");//Titulo de la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PeonN_H7 = new javax.swing.JLabel();
        PeonN_G7 = new javax.swing.JLabel();
        PeonN_F7 = new javax.swing.JLabel();
        PeonN_E7 = new javax.swing.JLabel();
        PeonN_D7 = new javax.swing.JLabel();
        PeonN_C7 = new javax.swing.JLabel();
        PeonN_B7 = new javax.swing.JLabel();
        PeonN_A7 = new javax.swing.JLabel();
        TorreN_H8 = new javax.swing.JLabel();
        TorreN_A8 = new javax.swing.JLabel();
        ReyN_E8 = new javax.swing.JLabel();
        AlfilN_F8 = new javax.swing.JLabel();
        AlfilN_C8 = new javax.swing.JLabel();
        CaballoN_G8 = new javax.swing.JLabel();
        CaballoN_B8 = new javax.swing.JLabel();
        ReinaN_D8 = new javax.swing.JLabel();
        TorreW_A1 = new javax.swing.JLabel();
        TorreW_H1 = new javax.swing.JLabel();
        CaballoW_B1 = new javax.swing.JLabel();
        CaballoW_G1 = new javax.swing.JLabel();
        AlfilW_C1 = new javax.swing.JLabel();
        AlfilW_F1 = new javax.swing.JLabel();
        ReinaW_D1 = new javax.swing.JLabel();
        ReyW_E1 = new javax.swing.JLabel();
        PeonW_A2 = new javax.swing.JLabel();
        PeonW_B2 = new javax.swing.JLabel();
        PeonW_C2 = new javax.swing.JLabel();
        PeonW_D2 = new javax.swing.JLabel();
        PeonW_E2 = new javax.swing.JLabel();
        PeonW_F2 = new javax.swing.JLabel();
        PeonW_G2 = new javax.swing.JLabel();
        PeonW_H2 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        C6 = new javax.swing.JLabel();
        C5 = new javax.swing.JLabel();
        C4 = new javax.swing.JLabel();
        C3 = new javax.swing.JLabel();
        D6 = new javax.swing.JLabel();
        D5 = new javax.swing.JLabel();
        D4 = new javax.swing.JLabel();
        D3 = new javax.swing.JLabel();
        E6 = new javax.swing.JLabel();
        E5 = new javax.swing.JLabel();
        E4 = new javax.swing.JLabel();
        E3 = new javax.swing.JLabel();
        F6 = new javax.swing.JLabel();
        F5 = new javax.swing.JLabel();
        F4 = new javax.swing.JLabel();
        F3 = new javax.swing.JLabel();
        G6 = new javax.swing.JLabel();
        G5 = new javax.swing.JLabel();
        G4 = new javax.swing.JLabel();
        G3 = new javax.swing.JLabel();
        H6 = new javax.swing.JLabel();
        H5 = new javax.swing.JLabel();
        H4 = new javax.swing.JLabel();
        H3 = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        E1 = new javax.swing.JLabel();
        E2 = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        F2 = new javax.swing.JLabel();
        G1 = new javax.swing.JLabel();
        G2 = new javax.swing.JLabel();
        H1 = new javax.swing.JLabel();
        H2 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        B7 = new javax.swing.JLabel();
        B8 = new javax.swing.JLabel();
        C8 = new javax.swing.JLabel();
        C7 = new javax.swing.JLabel();
        D8 = new javax.swing.JLabel();
        D7 = new javax.swing.JLabel();
        E8 = new javax.swing.JLabel();
        E7 = new javax.swing.JLabel();
        F8 = new javax.swing.JLabel();
        F7 = new javax.swing.JLabel();
        G8 = new javax.swing.JLabel();
        G7 = new javax.swing.JLabel();
        H8 = new javax.swing.JLabel();
        H7 = new javax.swing.JLabel();
        FondoTablero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PeonN_H7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonNegro.png"))); // NOI18N
        getContentPane().add(PeonN_H7, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 100, 50, 55));

        PeonN_G7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonNegro.png"))); // NOI18N
        getContentPane().add(PeonN_G7, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 100, 50, 55));

        PeonN_F7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonNegro.png"))); // NOI18N
        getContentPane().add(PeonN_F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 50, 55));

        PeonN_E7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonNegro.png"))); // NOI18N
        getContentPane().add(PeonN_E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 100, 50, 55));

        PeonN_D7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonNegro.png"))); // NOI18N
        getContentPane().add(PeonN_D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 100, 50, 55));

        PeonN_C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonNegro.png"))); // NOI18N
        getContentPane().add(PeonN_C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 100, 50, 55));

        PeonN_B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonNegro.png"))); // NOI18N
        getContentPane().add(PeonN_B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 100, 50, 55));

        PeonN_A7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonNegro.png"))); // NOI18N
        PeonN_A7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeonN_A7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PeonN_A7MouseEntered(evt);
            }
        });
        getContentPane().add(PeonN_A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 100, 50, 55));

        TorreN_H8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TorreNegro.png"))); // NOI18N
        getContentPane().add(TorreN_H8, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 48, 50, 55));

        TorreN_A8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TorreNegro.png"))); // NOI18N
        getContentPane().add(TorreN_A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 48, 50, 55));

        ReyN_E8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReyNegro.png"))); // NOI18N
        getContentPane().add(ReyN_E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 48, 50, 55));

        AlfilN_F8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AlfilNegro.png"))); // NOI18N
        getContentPane().add(AlfilN_F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 48, 50, 55));

        AlfilN_C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AlfilNegro.png"))); // NOI18N
        getContentPane().add(AlfilN_C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 48, 50, 55));

        CaballoN_G8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CaballoNegro.png"))); // NOI18N
        getContentPane().add(CaballoN_G8, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 48, 50, 55));

        CaballoN_B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CaballoNegro.png"))); // NOI18N
        getContentPane().add(CaballoN_B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 49, 50, 55));

        ReinaN_D8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReinaNegra.png"))); // NOI18N
        getContentPane().add(ReinaN_D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 48, 50, 55));

        TorreW_A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TorreBlanca.png"))); // NOI18N
        getContentPane().add(TorreW_A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 407, 50, 55));

        TorreW_H1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TorreBlanca.png"))); // NOI18N
        getContentPane().add(TorreW_H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 407, 50, 55));

        CaballoW_B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CaballoBlanco.png"))); // NOI18N
        getContentPane().add(CaballoW_B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 407, 50, 55));

        CaballoW_G1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CaballoBlanco.png"))); // NOI18N
        getContentPane().add(CaballoW_G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 407, 50, 55));

        AlfilW_C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AlfilBlanco.png"))); // NOI18N
        getContentPane().add(AlfilW_C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 407, 50, 55));

        AlfilW_F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AlfilBlanco.png"))); // NOI18N
        getContentPane().add(AlfilW_F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 407, 50, 55));

        ReinaW_D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReinaBlanca.png"))); // NOI18N
        getContentPane().add(ReinaW_D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 407, 50, 55));

        ReyW_E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReyBlanco.png"))); // NOI18N
        getContentPane().add(ReyW_E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 407, 50, 55));

        PeonW_A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonBlanco.png"))); // NOI18N
        getContentPane().add(PeonW_A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 355, 50, 55));

        PeonW_B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonBlanco.png"))); // NOI18N
        getContentPane().add(PeonW_B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 355, 50, 55));

        PeonW_C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonBlanco.png"))); // NOI18N
        getContentPane().add(PeonW_C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 355, 50, 55));

        PeonW_D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonBlanco.png"))); // NOI18N
        getContentPane().add(PeonW_D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 355, 50, 55));

        PeonW_E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonBlanco.png"))); // NOI18N
        getContentPane().add(PeonW_E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 355, 50, 55));

        PeonW_F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonBlanco.png"))); // NOI18N
        getContentPane().add(PeonW_F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 355, 50, 55));

        PeonW_G2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonBlanco.png"))); // NOI18N
        getContentPane().add(PeonW_G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 355, 50, 55));

        PeonW_H2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PeonBlanco.png"))); // NOI18N
        getContentPane().add(PeonW_H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 355, 50, 55));

        A6.setForeground(new java.awt.Color(242, 242, 242));
        getContentPane().add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 154, 52, 50));
        getContentPane().add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 205, 52, 50));
        getContentPane().add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 255, 52, 50));
        getContentPane().add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 307, 52, 50));
        getContentPane().add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 155, 52, 50));
        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 205, 52, 50));
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 255, 52, 50));
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 307, 52, 50));
        getContentPane().add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 155, 52, 50));
        getContentPane().add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 205, 52, 50));
        getContentPane().add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 255, 52, 50));
        getContentPane().add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 307, 52, 50));
        getContentPane().add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 155, 52, 50));
        getContentPane().add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 205, 52, 50));
        getContentPane().add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 255, 52, 50));
        getContentPane().add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 307, 52, 50));
        getContentPane().add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 155, 52, 50));
        getContentPane().add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 205, 52, 50));
        getContentPane().add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 255, 52, 50));
        getContentPane().add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 307, 52, 50));
        getContentPane().add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 155, 52, 50));
        getContentPane().add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 205, 52, 50));
        getContentPane().add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 255, 52, 50));
        getContentPane().add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 307, 52, 50));
        getContentPane().add(G6, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 155, 52, 50));
        getContentPane().add(G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 205, 52, 50));
        getContentPane().add(G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 255, 52, 50));
        getContentPane().add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 307, 52, 50));
        getContentPane().add(H6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 155, 52, 50));
        getContentPane().add(H5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 205, 52, 50));
        getContentPane().add(H4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 255, 52, 50));
        getContentPane().add(H3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 307, 52, 50));
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 410, 52, 50));
        getContentPane().add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 357, 52, 50));
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 407, 52, 50));
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 355, 52, 50));
        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 407, 52, 50));
        getContentPane().add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 355, 52, 50));
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 407, 52, 50));
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 355, 52, 50));
        getContentPane().add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 407, 52, 50));
        getContentPane().add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 355, 52, 50));
        getContentPane().add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 407, 52, 50));
        getContentPane().add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 356, 52, 50));
        getContentPane().add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 407, 52, 50));
        getContentPane().add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 355, 52, 50));
        getContentPane().add(H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 407, 52, 50));
        getContentPane().add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 358, 52, 50));
        getContentPane().add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 48, 52, 50));
        getContentPane().add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 100, 52, 50));
        getContentPane().add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 102, 52, 50));
        getContentPane().add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 52, 52, 50));
        getContentPane().add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 52, 52, 50));
        getContentPane().add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 102, 52, 50));
        getContentPane().add(D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 52, 52, 50));
        getContentPane().add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 102, 52, 50));
        getContentPane().add(E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 52, 52, 50));
        getContentPane().add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 102, 52, 50));
        getContentPane().add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 52, 52, 50));
        getContentPane().add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 102, 52, 50));
        getContentPane().add(G8, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 52, 52, 50));
        getContentPane().add(G7, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 102, 52, 50));
        getContentPane().add(H8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 52, 52, 50));
        getContentPane().add(H7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 102, 52, 50));

        FondoTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoTablero.png"))); // NOI18N
        getContentPane().add(FondoTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 512, 512));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PeonN_A7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeonN_A7MouseClicked
       Peon N=new Peon("N", this);
       N.setPosicion(A7.getLocation());
       N.Mover();
    }//GEN-LAST:event_PeonN_A7MouseClicked

    private void PeonN_A7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeonN_A7MouseEntered
        Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        PeonN_A7.setCursor(cursor);
    }//GEN-LAST:event_PeonN_A7MouseEntered
    private Point[][] Tablero=new Point[8][8];
    public void LlenarMatriz(){
        //FILA 8
        Tablero[0][0]=A8.getLocation();
        Tablero[0][1]=B8.getLocation();
        Tablero[0][2]=C8.getLocation();
        Tablero[0][3]=D8.getLocation();
        Tablero[0][4]=E8.getLocation();
        Tablero[0][5]=F8.getLocation();
        Tablero[0][6]=G8.getLocation();
        Tablero[0][7]=H8.getLocation();
        //FILA 7
        Tablero[1][0]=A7.getLocation();
        Tablero[1][1]=B7.getLocation();
        Tablero[1][2]=C7.getLocation();
        Tablero[1][3]=D7.getLocation();
        Tablero[1][4]=E7.getLocation();
        Tablero[1][5]=F7.getLocation();
        Tablero[1][6]=G7.getLocation();
        Tablero[1][7]=H7.getLocation();
        //FILA 6
        Tablero[2][0]=A6.getLocation();
        Tablero[2][1]=B6.getLocation();
        Tablero[2][2]=C6.getLocation();
        Tablero[2][3]=D6.getLocation();
        Tablero[2][4]=E6.getLocation();
        Tablero[2][5]=F6.getLocation();
        Tablero[2][6]=G6.getLocation();
        Tablero[2][7]=H6.getLocation();
        //FILA 5
        Tablero[3][0]=A5.getLocation();
        Tablero[3][1]=B5.getLocation();
        Tablero[3][2]=C5.getLocation();
        Tablero[3][3]=D5.getLocation();
        Tablero[3][4]=E5.getLocation();
        Tablero[3][5]=F5.getLocation();
        Tablero[3][6]=G5.getLocation();
        Tablero[3][7]=H5.getLocation();
        //FILA 4
        Tablero[4][0]=A4.getLocation();
        Tablero[4][1]=B4.getLocation();
        Tablero[4][2]=C4.getLocation();
        Tablero[4][3]=D4.getLocation();
        Tablero[4][4]=E4.getLocation();
        Tablero[4][5]=F4.getLocation();
        Tablero[4][6]=G4.getLocation();
        Tablero[4][7]=H4.getLocation();
        //FILA 3
        Tablero[5][0]=A3.getLocation();
        Tablero[5][1]=B3.getLocation();
        Tablero[5][2]=C3.getLocation();
        Tablero[5][3]=D3.getLocation();
        Tablero[5][4]=E3.getLocation();
        Tablero[5][5]=F3.getLocation();
        Tablero[5][6]=G3.getLocation();
        Tablero[5][7]=H3.getLocation();
        //FILA 2
        Tablero[6][0]=A2.getLocation();
        Tablero[6][1]=B2.getLocation();
        Tablero[6][2]=C2.getLocation();
        Tablero[6][3]=D2.getLocation();
        Tablero[6][4]=E2.getLocation();
        Tablero[6][5]=F2.getLocation();
        Tablero[6][6]=G2.getLocation();
        Tablero[6][7]=H2.getLocation();
        //FILA 1
        Tablero[7][0]=A1.getLocation();
        Tablero[7][1]=B1.getLocation();
        Tablero[7][2]=C1.getLocation();
        Tablero[7][3]=D1.getLocation();
        Tablero[7][4]=E1.getLocation();
        Tablero[7][5]=F1.getLocation();
        Tablero[7][6]=G1.getLocation();
        Tablero[7][7]=H1.getLocation();
    }
    public JLabel getA7(){
        return A7;
    }
    public JLabel getB7(){
        return B7;
    }
    public JLabel getC7(){
        return C7;
    }
    public JLabel getD7(){
        return D7;
    }
    public JLabel getE7(){
        return E7;
    }
    public JLabel getF7(){
        return F7;
    }
    public JLabel getG7(){
        return G7;
    }
    public JLabel getH7(){
        return H7;
    }    
    public void setBorderA6(){
        A6.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getA6(){
        return A6;
    }
    public void setBorderA5(){
        A5.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getA5(){
        return A5;
    }
    public void setBorderB5(){
        B5.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getB5(){
        return B5;
    }
    public void setBorderB6(){
        B6.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getB6(){
        return B6;
    }
    public void setBorderC5(){
        C5.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getC5(){
        return C5;
    }
    public void setBorderC6(){
        C6.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getC6(){
        return C6;
    }
    public void setBorderD5(){
        D5.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getD5(){
        return D5;
    }
    public void setBorderD6(){
        D6.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getD6(){
        return D6;
    }
    public void setBorderE5(){
        E5.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getE5(){
        return E5;
    }
    public void setBorderE6(){
        E6.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getE6(){
        return E6;
    } 
    public void setBorderF5(){
        F5.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getF5(){
        return F5;
    }
    public void setBorderF6(){
        F6.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getF6(){
        return F6;
    }
    public void setBorderG5(){
        G5.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getG5(){
        return G5;
    }
    public void setBorderG6(){
        G6.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getG6(){
        return G6;
    }
    public void setBorderH5(){
        H5.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getH5(){
        return H5;
    }
    public void setBorderH6(){
        H6.setBorder(BorderFactory.createLineBorder(Color.red, 2));
    }
    public JLabel getH6(){
        return H6;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel AlfilN_C8;
    private javax.swing.JLabel AlfilN_F8;
    private javax.swing.JLabel AlfilW_C1;
    private javax.swing.JLabel AlfilW_F1;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel B7;
    private javax.swing.JLabel B8;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel C3;
    private javax.swing.JLabel C4;
    private javax.swing.JLabel C5;
    private javax.swing.JLabel C6;
    private javax.swing.JLabel C7;
    private javax.swing.JLabel C8;
    private javax.swing.JLabel CaballoN_B8;
    private javax.swing.JLabel CaballoN_G8;
    private javax.swing.JLabel CaballoW_B1;
    private javax.swing.JLabel CaballoW_G1;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel D3;
    private javax.swing.JLabel D4;
    private javax.swing.JLabel D5;
    private javax.swing.JLabel D6;
    private javax.swing.JLabel D7;
    private javax.swing.JLabel D8;
    private javax.swing.JLabel E1;
    private javax.swing.JLabel E2;
    private javax.swing.JLabel E3;
    private javax.swing.JLabel E4;
    private javax.swing.JLabel E5;
    private javax.swing.JLabel E6;
    private javax.swing.JLabel E7;
    private javax.swing.JLabel E8;
    private javax.swing.JLabel F1;
    private javax.swing.JLabel F2;
    private javax.swing.JLabel F3;
    private javax.swing.JLabel F4;
    private javax.swing.JLabel F5;
    private javax.swing.JLabel F6;
    private javax.swing.JLabel F7;
    private javax.swing.JLabel F8;
    private javax.swing.JLabel FondoTablero;
    private javax.swing.JLabel G1;
    private javax.swing.JLabel G2;
    private javax.swing.JLabel G3;
    private javax.swing.JLabel G4;
    private javax.swing.JLabel G5;
    private javax.swing.JLabel G6;
    private javax.swing.JLabel G7;
    private javax.swing.JLabel G8;
    private javax.swing.JLabel H1;
    private javax.swing.JLabel H2;
    private javax.swing.JLabel H3;
    private javax.swing.JLabel H4;
    private javax.swing.JLabel H5;
    private javax.swing.JLabel H6;
    private javax.swing.JLabel H7;
    private javax.swing.JLabel H8;
    private javax.swing.JLabel PeonN_A7;
    private javax.swing.JLabel PeonN_B7;
    private javax.swing.JLabel PeonN_C7;
    private javax.swing.JLabel PeonN_D7;
    private javax.swing.JLabel PeonN_E7;
    private javax.swing.JLabel PeonN_F7;
    private javax.swing.JLabel PeonN_G7;
    private javax.swing.JLabel PeonN_H7;
    private javax.swing.JLabel PeonW_A2;
    private javax.swing.JLabel PeonW_B2;
    private javax.swing.JLabel PeonW_C2;
    private javax.swing.JLabel PeonW_D2;
    private javax.swing.JLabel PeonW_E2;
    private javax.swing.JLabel PeonW_F2;
    private javax.swing.JLabel PeonW_G2;
    private javax.swing.JLabel PeonW_H2;
    private javax.swing.JLabel ReinaN_D8;
    private javax.swing.JLabel ReinaW_D1;
    private javax.swing.JLabel ReyN_E8;
    private javax.swing.JLabel ReyW_E1;
    private javax.swing.JLabel TorreN_A8;
    private javax.swing.JLabel TorreN_H8;
    private javax.swing.JLabel TorreW_A1;
    private javax.swing.JLabel TorreW_H1;
    // End of variables declaration//GEN-END:variables
}
